In [71]:
import pandas as pd

In [72]:
df=pd.read_csv("car-sales-extended.csv")
df

       Make Colour  Odometer (KM)  Doors  Price
0     Honda  White          35431      4  15323
1       BMW   Blue         192714      5  19943
2     Honda  White          84714      4  28343
3    Toyota  White         154365      4  13434
4    Nissan   Blue         181577      3  14043
..      ...    ...            ...    ...    ...
995  Toyota  Black          35820      4  32042
996  Nissan  White         155144      3   5716
997  Nissan   Blue          66604      4  31570
998   Honda  White         215883      4   4001
999  Toyota   Blue         248360      4  12732

[1000 rows x 5 columns]

In [73]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Make           1000 non-null   object
 1   Colour         1000 non-null   object
 2   Odometer (KM)  1000 non-null   int64
 3   Doors          1000 non-null   int64
 4   Price          1000 non-null   int64
dtypes: int64(3), object(2)
memory usage: 39.2+ KB

In [74]:
df.describe()

       Odometer (KM)        Doors         Price
count    1000.000000  1000.000000   1000.000000
mean   131073.708000     4.014000  16045.665000
std     68859.723885     0.379405   8630.794219
min     10148.000000     3.000000   2796.000000
25%     71238.000000     4.000000   9481.500000
50%    131202.000000     4.000000  14264.000000
75%    192372.750000     4.000000  20738.750000
max    249860.000000     5.000000  52458.000000

In [75]:
df['Make']=df['Make'].str.replace('Toyota','0').str.replace('Honda','1').str.replace('Nissan','2').str.replace('BMW','3').astype(int)
df['Colour']=df['Colour'].str.replace('White','0').str.replace('Blue','1').str.replace('Black','2').str.replace('Red','3').str.replace('Green','4').astype(int)

In [76]:
df

     Make  Colour  Odometer (KM)  Doors  Price
0       1       0          35431      4  15323
1       3       1         192714      5  19943
2       1       0          84714      4  28343
3       0       0         154365      4  13434
4       2       1         181577      3  14043
..    ...     ...            ...    ...    ...
995     0       2          35820      4  32042
996     2       0         155144      3   5716
997     2       1          66604      4  31570
998     1       0         215883      4   4001
999     0       1         248360      4  12732

[1000 rows x 5 columns]

In [77]:
X = df.drop('Price',axis=1)
y=df['Price'].copy()

In [78]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

lr.fit(X_train,y_train)

LinearRegression()

In [79]:
print("Train:",lr.score(X_train,y_train)) # this is underfitting so to reduce it
print("Test :",lr.score(X_test,y_test))    # we can use more complex mmodel like random forest regressor
                                        # or adding useful features -new columns

Train: 0.24097288188669774
Test : 0.3483022995053606

In [80]:
preds = lr.predict(X_test)

In [81]:
from sklearn.metrics import root_mean_squared_error

In [82]:
preds=lr.predict(X_test)

In [83]:
root_mean_squared_error(y_test,preds)   # measures average prediction error
# so, on average, the predicted car prices differ from
# the actual prices by apprxmtly 7,718 units
#again we can reduce it by adding useful features(columns) or using other complex model

7718.241355006739

In [84]:
# creating a small  dataset manually

In [85]:
import pandas as pd

# create data
data = {
    "Height_cm": [170, 160, 180, 155, 172],
    "Weight_kg": [65, 50, 75, 48, 68],
    "Hair_Length_cm": [5, 25, 7, 30, 6],
    "Voice_Pitch": ["Low", "High", "Low", "High", "Low"],
    "Gender": ["Boy", "Girl", "Boy", "Girl", "Boy"]
}

# create DataFrame
df = pd.DataFrame(data)

print(df)

   Height_cm  Weight_kg  Hair_Length_cm Voice_Pitch Gender
0        170         65               5         Low    Boy
1        160         50              25        High   Girl
2        180         75               7         Low    Boy
3        155         48              30        High   Girl
4        172         68               6         Low    Boy

In [86]:
df['Voice_Pitch']=df['Voice_Pitch'].str.replace('Low','0').str.replace('High','1').astype(int)
df['Gender']=df['Gender'].str.replace('Boy','0').str.replace('Girl','1').astype(int)

In [87]:
X = df.drop('Gender', axis=1)
y = df['Gender']

In [88]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [89]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

In [90]:
model.fit(X_train, y_train)

LogisticRegression()

In [91]:
preds = model.predict(X_test)

In [92]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, preds)

print("Accuracy:", accuracy)

Accuracy: 1.0

In [93]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, preds)

print(cm)

[[1]]

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:407: UserWarning: A single label was found in 'y_true' and 'y_pred'. For the confusion matrix to have the correct shape, use the 'labels' parameter to pass all known labels.
  warnings.warn(

In [94]:
# logistic regression model achieved 100% accuracy on the test set
# but the dataset is extremely small so this result is not sufficient
# to conclude that  model generalizes well to unseen data.